# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "fin-dev-tfstate"
    key            = "./terraform.tfstate"
    region         = "us-east-2"
    encrypt        = true
    dynamodb_table = "fin-dev-locks"
  }
}
